# Generated by Django 6.0.2 on 2026-02-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('desc', models.CharField(max_length=256)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='series/')),
                ('seasons', models.IntegerField()),
                ('episodes', models.IntegerField()),
            ],
        ),
    ]
