# Generated by Django 6.0.2 on 2026-02-17 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_movie_video_serie_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('video', models.FileField(blank=True, null=True, upload_to='episodes/')),
                ('season_number', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_list', to='api.serie')),
            ],
        ),
    ]
