# Generated by Django 6.0.2 on 2026-02-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('sci-fi', 'Sci-Fi'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('animation', 'Animation'), ('documentary', 'Documentary'), ('adventure', 'Adventure'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery')], default='drama', max_length=32),
        ),
        migrations.AddField(
            model_name='serie',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('sci-fi', 'Sci-Fi'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('animation', 'Animation'), ('documentary', 'Documentary'), ('adventure', 'Adventure'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery')], default='drama', max_length=32),
        ),
    ]
